stack_name: "MalLab-Demo"

# sample_src_path: "https://github.com/HuskyHacks/PMAT-labs/archive/refs/heads/main.zip"
# sample_dest_path: "C:\\Users\\analyst\\Desktop\\PMAT-labs.zip"

sample_src_path: "https://github.com/ytisf/theZoo/archive/refs/heads/master.zip"
sample_dest_path: "C:\\Users\\analyst\\Desktop\\theMalwareZoo.zip"

flare_vm_box: "lupulvp/FlareVM-Win10Enterprise22H2"
flare_vm_box_version: "2.0.0"
flare_vm_memory: 8192
flare_vm_cpus: 4

remnux_vm_box: "lupulvp/REMnux-v7-focal"
remnux_vm_box_version: "1.0.0"
remnux_vm_memory: 1024
remnux_vm_cpus: 1